version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  user-management:
    build: ./UserManagementService
    ports:
      - 3001:3001
    depends_on:
      - mongo

  product-management:
    build: ./ProductManagementService
    ports:
      - 3003:3003
    depends_on:
      - mongo

  payment-management:
    build: ./PaymentManagementService
    ports:
      - 3004:3004
    depends_on:
      - mongo

  order-management:
    build: ./OrderManagementService
    ports:
      - 3005:3005
    depends_on:
      - mongo

  feedback-management:
    build: ./FeedbackManagementService
    ports:
      - 3006:3006
    depends_on:
      - mongo

  web-ui:
    build: ./Web-ui
    ports:
      - 3000:3000

    environment:
      - REACT_APP_USER_MANAGEMENT_API_URL=http://user-management:3001
      - REACT_APP_PRODUCT_MANAGEMENT_API_URL=http://product-management:3003
      - REACT_APP_PAYMENT_MANAGEMENT_API_URL=http://payment-management:3004
      - REACT_APP_ORDER_MANAGEMENT_API_URL=http://order-management:3005
      - REACT_APP_FEEDBACK_MANAGEMENT_API_URL=http://feedback-management:3006

    depends_on:
      - user-management
      - payment-management

volumes:
  mongodb_data:
